project_name: goful
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: goful
    goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^chore'
      - '^test'
      - '^style'
      - Merge pull request
      - Merge branch
